"""Shell completion script templates for zsh, bash, and fish."""

from __future__ import annotations

ZSH_SCRIPT = r"""#compdef swe
# swe zsh completion — generated by `swe autocomplete zsh`

_swe() {
    local -a lines comps
    local out last directive cand desc

    # Forward current words to swe's __complete command
    out=$(swe __complete ${words[2,-1]} 2>/dev/null)
    if [[ -z "${out}" ]]; then
        return 1
    fi

    # Split output into lines
    lines=(${(f)out})
    last=${lines[-1]}

    # Parse directive from last line (:N format)
    if [[ "${last}" = :* ]]; then
        directive=${last[2,-1]}
        lines=(${lines[1,-2]})
    else
        directive=0
    fi

    # Format completions: "candidate\tdescription" -> "candidate:description"
    for line in ${lines}; do
        cand=${line%%$'\t'*}
        desc=${line##*$'\t'}
        if [[ "${cand}" = "${desc}" ]]; then
            comps+=("${cand}")
        else
            comps+=("${cand}:${desc}")
        fi
    done

    _describe 'swe' comps

    # Directive 4 = NoFileComp — suppress file fallback
    if (( directive & 4 )); then
        return 1
    fi
    return 0
}

compdef _swe swe
"""

BASH_SCRIPT = r"""# swe bash completion — generated by `swe autocomplete bash`

_swe_completion() {
    local cur prev words out directive
    cur="${COMP_WORDS[COMP_CWORD]}"
    
    # Build word list (everything after "swe" up to cursor)
    local -a swe_words
    swe_words=("${COMP_WORDS[@]:1:COMP_CWORD}")
    
    # Call swe's __complete command
    out=$(swe __complete "${swe_words[@]}" 2>/dev/null)
    if [[ -z "${out}" ]]; then
        return 0
    fi
    
    # Parse output: candidates are tab-separated "name\tdesc", last line is :directive
    local -a lines
    local last
    lines=(${(f)out} 2>/dev/null || out)
    # Fallback: split on newlines
    if [[ ${#lines[@]} -eq 0 ]]; then
        while IFS= read -r line; do
            lines+=("$line")
        done <<< "$out"
    fi
    
    last="${lines[-1]}"
    if [[ "${last}" = :* ]]; then
        directive="${last:1}"
        unset 'lines[-1]'
    else
        directive=0
    fi
    
    # Extract just the candidate names (before tab)
    local comps=""
    for line in "${lines[@]}"; do
        local cand="${line%%$'\t'*}"
        if [[ -n "${cand}" ]]; then
            comps="${comps} ${cand}"
        fi
    done
    
    COMPREPLY=($(compgen -W "${comps}" -- "${cur}"))
    
    # Directive 4 = NoFileComp
    if (( directive & 4 )); then
        return 1
    fi
    return 0
}

complete -F _swe_completion swe
"""

FISH_SCRIPT = r"""# swe fish completion — generated by `swe autocomplete fish`

function __swe_complete
    # Get words after "swe" up to cursor
    set -l words (commandline -opc)[2..-1]
    if test (commandline -ct) != ""
        set words $words (commandline -ct)
    end
    
    # Call swe's __complete command
    set -l out (swe __complete $words 2>/dev/null)
    if test -z "$out"
        return
    end
    
    # Parse output: candidates are tab-separated, last line is :directive
    for line in $out
        if string match -q ':*' -- $line
            continue
        end
        # Extract candidate (before tab)
        set -l cand (string split \t -- $line)[1]
        if test -n "$cand"
            echo $cand
        end
    end
end

complete -c swe -f -a "(__swe_complete)"
"""

# (shell_name, script_content, profile_path, profile_instructions)
SHELL_CONFIGS = {
    "zsh": {
        "script": ZSH_SCRIPT,
        "filename": "swe.zsh",
        "profile": "~/.zshrc",
        "profile_instructions": "source ~/.zshrc",
    },
    "bash": {
        "script": BASH_SCRIPT,
        "filename": "swe.bash",
        "profile": "~/.bashrc",
        "profile_instructions": "source ~/.bashrc",
    },
    "fish": {
        "script": FISH_SCRIPT,
        "filename": "swe.fish",
        "profile": "~/.config/fish/config.fish",
        "profile_instructions": "source ~/.config/fish/config.fish",
    },
}

SUPPORTED_SHELLS = list(SHELL_CONFIGS.keys())
