blank_issues_enabled: false
contact_links:
  - name: Question / discussion
    url: https://github.com/c-wenlong/quiver/discussions
    about: Ask questions or share ideas that aren't bugs or feature requests
